baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'BlogChain'
theme = "paper"


[params]
# color style
color = 'linen' # linen, wheat, gray, light

# header social icons
twitter = 'okan_buidl'                          # twitter.com/YOUR_TWITTER_ID
github = 'demirbey05'                           # github.com/YOUR_GITHUB_ID
linkedin = 'h%C3%BCseyin-okan-demir-987279168/' # linkedin.com/in/YOUR_LINKEDIN_ID
rss = true                                      # show rss icon

# home page profile
name = 'Huseyin Okan Demir'
bio = 'Some programming stuffs'
avatar = 'huseyinokand@gmail.com'


# misc
disableHLJS = true  # disable highlight.js
monoDarkIcon = true # show monochrome dark mode icon
math = true         # enable KaTeX math typesetting globally


[menu]

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
